### ISSUE TITLE
Post sponsor thank yous on social media

### ISSUE THREAD

**Issue by rocketeerbkw** [TexasCamp/planning#3]
As per our prospectus, we need to thank our sponsors on social media. Last year we spread them out over awhile to keep spamming down and as a way to keep us coming up in peoples feeds.

Probably the easiest way to do that is sing up for buffer.com or another scheduling platform that offers a free plan. Can setup all the posts once to go out over the next two weeks.

Confirm that sponsors have paid before posting for them.

**Comment by ccjjmartin** [comment]
@rocketeerbkw Irma Martin has an account for scheduling tweets and has been working on creating all of them, then we can schedule them.
