### ISSUE TITLE
Create docs for speakers

### ISSUE THREAD

**Issue by rocketeerbkw** [TexasCamp/planning#6]
A small handout (and google doc) to give speakers that has useful information.

- Contact information for scheduling issues (late or can't make it, etc)
- Contact information for IT issues (TVs down, can't connect to HDMI, recording malfunction, etc)
- What speakers are required to bring (laptop, power, A/V connector, etc)
- When speakers should arrive (at least during the walkaround time right before?)
- How to record their session
- What to do after it's done (upload slides, etc)
- etc

**Comment by ccjjmartin** [comment]
@rocketeerbkw I think this is done.  Last night we emailed the speakers with all of this info.  Is there anything else to be done?
